apiVersion: v1
kind: ConfigMap
metadata:
  name: delta-properties
data:
  delta.properties: |
    # Add the contents of your delta.properties file here
    connector.name=delta-lake
    hive.metastore.uri=thrift://hive-metastore:9083
    hive.s3.aws-access-key=ewqewqewqewqewq
    hive.s3.aws-secret-key=AGQFjzMeqwewqewqewqwqmXs
    hive.s3.endpoint=http://130.1.1.1:9000
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-properties
data:
  Hive.properties: |
    # Add the contents of your Hive.properties file here
    connector.name=hive
    hive.metastore.uri=thrift://hive-metastore:9083
    hive.s3.aws-access-key=ewqewqewqewqewq
    hive.s3.aws-secret-key=AGQFjzMeqwewqewqewqwqmXs
  hive.s3.endpoint=http://130.1.1.1:9000
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false

